### ISSUE TITLE
Adding the gem makes my specs fail with reasons like "undefined method `modal_dialog_present?' for nil:NilClass"

### ISSUE THREAD

**Issue by jmuheim** [Casecommons/capybara-accessible#16]
I have added the gem, and this produces errors like this:

```
  1) Signing in user is signed up is possible to sign in using name
     Failure/Error: click_button 'Sign in'
     NoMethodError:
       undefined method `modal_dialog_present?' for nil:NilClass
     # /Users/josh/.rvm/gems/ruby-2.1.0@base/gems/capybara-accessible-0.2.1/lib/capybara/accessible/auditor.rb:20:in `modal_dialog_present?'
```

I also get database locked warnings:

```
Signing in
  user is signed up
Error during failsafe response: SQLite3::BusyException: database is locked: INSERT INTO "users" ("guest", "confirmed_at", "name", "created_at", "updated_at") VALUES (?, ?, ?, ?, ?)
  /Users/josh/.rvm/gems/ruby-2.1.0@base/gems/sqlite3-1.3.10/lib/sqlite3/statement.rb:108:in `step'
```

And a lot of element not found problems:

```
  27) File upload limits the size of an uploaded image
     Failure/Error: attach_file 'user_avatar', dummy_file_path('big_image.jpg')
     Capybara::ElementNotFound:
       Unable to find file field "user_avatar"
     # /Users/josh/.rvm/gems/ruby-2.1.0@base/gems/capybara-2.4.4/lib/capybara/node/finders.rb:41:in `block in find'
```

I'm on Rails 4.2. Is this gem still maintained and meant for current versions of Rails?

**Comment by ckundo** [comment]
I think this is a method that has been deprecated in capybara-webkit. Which driver are you using?

**Comment by jmuheim** [comment]
Poltergeist.

**Comment by ckundo** [comment]
@jmuheim we're defining that method here: https://github.com/Casecommons/capybara-accessible/blob/master/lib/capybara/accessible/auditor.rb#L19, but it looks like driver_adapter is not returning anything. I've been able to recreate this and will investigate.

**Comment by jmuheim** [comment]
Thank you.

**Comment by ckundo** [comment]
@nshah9 have you all seen this issue at all on your end?

**Comment by ckundo** [comment]
@jmuheim can you double check that you are specifying `:js` on your specs? They should look something like:

```ruby
feature "User signing up" do
  scenario "sees a success message", :js do
    <assertion>
  end
end
```
